version "4.10"

#include "zscript/gunsmithpouch/gunsmithpouch.zsc"
#include "zscript/gunsmithpouch/gunsmithpouch_bulk.zsc"
#include "zscript/gunsmithpouch/gunsmithpouch_hud.zsc"
#include "zscript/gunsmithpouch/gunsmithpouch_itemstorage.zsc"
#include "zscript/gunsmithpouch/gunsmithpouch_spawning.zsc"

#include "zscript/universalreloader/spawnHandler.zsc"

#include "zscript/universalreloader/items/universalReloader.zsc"

#include "zscript/universalreloader/recipes/reloaderRecipe.zsc"

#include "zscript/universalreloader/recipes/base/craftingMaterials.zsc"

#include "zscript/universalreloader/recipes/materials/rawBrass.zsc"
#include "zscript/universalreloader/recipes/materials/rawLead.zsc"
#include "zscript/universalreloader/recipes/materials/rawPlastic.zsc"
#include "zscript/universalreloader/recipes/materials/rawPowder.zsc"
#include "zscript/universalreloader/recipes/materials/rawSteel.zsc"
