// Struct for itemspawn information.
class URLSpawnItem play {
    // ID by string for spawner
    string spawnName;
    
    // ID by string for spawnees
    Array<URLSpawnItemEntry> spawnReplaces;
    
    // Whether or not to persistently spawn.
    bool isPersistent;
    
    bool replaceItem;

    string toString() {

        let replacements = "[";
        if (spawnReplaces.size()) {
            replacements = replacements..spawnReplaces[0].toString();

            for (let i = 1; i < spawnReplaces.size(); i++) {
                replacements = replacements..", "..spawnReplaces[i].toString();
            }
        }
        replacements = replacements.."]";


        return String.format("{ spawnName=%s, spawnReplaces=%s, isPersistent=%b, replaceItem=%b }", spawnName, replacements, isPersistent, replaceItem);
    }
}

class URLSpawnItemEntry play {
    string name;
    int    chance;

    string toString() {
        return String.format("{ name=%s, chance=%s }", name, chance >= 0 ? "1/"..(chance + 1) : "never");
    }
}

// Struct for passing useinformation to ammunition.
class URLSpawnAmmo play {
    // ID by string for the header ammo.
    string ammoName;
    
    // ID by string for weapons using that ammo.
    Array<string> weaponNames;
    
    string toString() {

        let weapons = "[";
        if (weaponNames.size()) {
            weapons = weapons..weaponNames[0];

            for (let i = 1; i < weaponNames.size(); i++) {
                weapons = weapons..", "..weaponNames[i];
            }
        }
        weapons = weapons.."]";

        return String.format("{ ammoName=%s, weaponNames=%s }", ammoName, weapons);
    }
}



// One handler to rule them all.
class URLSpawnHandler : EventHandler {

    // List of persistent classes to completely ignore.
    // This -should- mean this mod has no performance impact.
    static const class<actor> blacklist[] = {
        "HDSmoke",
        "BloodTrail",
        "CheckPuff",
        "WallChunk",
        "HDBulletPuff",
        "HDFireballTail",
        "ReverseImpBallTail",
        "HDSmokeChunk",
        "ShieldSpark",
        "HDFlameRed",
        "HDMasterBlood",
        "PlantBit",
        "HDBulletActor",
        "HDLadderSection"
    };

    // List of weapon-ammo associations.
    // Used for ammo-use association on ammo spawn (happens very often).
    array<URLSpawnAmmo> ammoSpawnList;

    // List of item-spawn associations.
    // used for item-replacement on mapload.
    array<URLSpawnItem> itemSpawnList;

    Array<HDRel_Recipe> recipes;

    bool cvarsAvailable;

    // appends an entry to itemSpawnList;
    void addItem(string name, Array<URLSpawnItemEntry> replacees, bool persists, bool rep=true) {

        if (hd_debug) {
            let msg = "Adding "..(persists ? "Persistent" : "Non-Persistent").." Replacement Entry for "..name..": ["..replacees[0].toString();

            if (replacees.size() > 1) {
                for (let i = 1; i < replacees.size(); i++) msg = msg..", "..replacees[i].toString();
            }

            console.printf(msg.."]");
        }

        // Creates a new struct;
        URLSpawnItem spawnee = URLSpawnItem(new('URLSpawnItem'));

        // Populates the struct with relevant information,
        spawnee.spawnName = name;
        spawnee.isPersistent = persists;
        spawnee.replaceItem = rep;

        for (int i = 0; i < replacees.size(); i++) {
            spawnee.spawnReplaces.push(replacees[i]);
        }

        // Pushes the finished struct to the array.
        itemSpawnList.push(spawnee);
    }

    URLSpawnItemEntry addItemEntry(string name, int chance) {
        // Creates a new struct;
        URLSpawnItemEntry spawnee = URLSpawnItemEntry(new('URLSpawnItemEntry'));
        spawnee.name = name.makelower();
        spawnee.chance = chance;
        return spawnee;
    }

    // appends an entry to ammoSpawnList;
    void addAmmo(string name, Array<string> weapons) {

        // Creates a new struct;
        URLSpawnAmmo spawnee = URLSpawnAmmo(new('URLSpawnAmmo'));
        spawnee.ammoName = name.makelower();

        // Populates the struct with relevant information,
        for (int i = 0; i < weapons.size(); i++) {
            spawnee.weaponNames.push(weapons[i].makelower());
        }

        // Pushes the finished struct to the array.
        ammoSpawnList.push(spawnee);
    }

    void addRecipe(string amcls,
        class<HDRel_ProjectileMaterial> projMat, int projCost, double projProd,
        class<HDRel_CasingMaterial> casingMat,   int csgCost,  double csgProd,
        class<HDRel_PowderMaterial> powderMat,   int pwdCost,  double pwdProd,
        double speed
    ) {
        HDRel_Recipe r;

        if (r = HDRel_Recipe.TryCreate(amcls,
            projMat, projCost, projProd,
            casingMat, csgCost, csgProd,
            powderMat, pwdCost, pwdProd,
            speed)
        ) {
            if (hd_debug) console.printf("Adding Universal Reloader Crafting Recipe for "..amcls);

            recipes.push(r);
        }
    }


    // Populates the replacement and association arrays.
    void init() {
        
        cvarsAvailable = true;

        //---------------------
        // Crafting Materials
        //---------------------

        Array<String> mat_brass;
        mat_brass.push("HDUniversalReloader");
        addAmmo("HDRel_RawBrass", mat_brass);

        Array<String> mat_lead;
        mat_lead.push("HDUniversalReloader");
        addAmmo("HDRel_RawLead", mat_lead);

        Array<String> mat_plastic;
        mat_plastic.push("HDUniversalReloader");
        addAmmo("HDRel_RawPlastic", mat_plastic);

        Array<String> mat_powder;
        mat_powder.push("HDUniversalReloader");
        addAmmo("HDRel_RawPowder", mat_powder);

        //---------------------
        // Crafting Recipes               Projectile mat, cost, produced; CasingmMat, cost, produced; Powder mat, cost, produced; Speed.
        //---------------------

        // VANILLA HDEST

        // 9mm
        addRecipe("HDPistolAmmo",         "HDRel_RawLead", 2, 1.00, "HDRel_RawPlastic", 1, 0.75, "HDRel_RawPowder", 1, 0.50, 1.50);
        addRecipe("HDSpent9mm",           null,            0, 0.00, "HDRel_RawPlastic", 0, 0.75, null,              0, 0.00, 1.50);

        // .355
        addRecipe("HDRevolverAmmo",       "HDRel_RawLead", 2, 1.00, "HDRel_RawPlastic", 1, 0.70, "HDRel_RawPowder", 2, 1.25, 1.00);
        addRecipe("HDSpent355",           null,            0, 0.00, "HDRel_RawPlastic", 0, 0.70, null,              0, 0.00, 1.00);

        // 12ga Shells
        addRecipe("HDShellAmmo",          "HDRel_RawLead", 4, 3.00, "HDRel_RawPlastic", 2, 1.00, "HDRel_RawPowder", 1, 0.50, 1.00);
        addRecipe("HDSpentShell",         null,            0, 0.00, "HDRel_RawPlastic", 0, 1.00, null,              0, 0.00, 1.00);

        // 4.26mm
        addRecipe("FourMilAmmo",          "HDRel_RawLead", 0, 1.00, null,               0, 0.00, "HDRel_RawPowder", 0, 1.00, 5.00);

        // 7.76mm
        addRecipe("SevenMilAmmo",         "HDRel_RawLead", 2, 1.50, "HDRel_RawBrass",   2, 1.75, "HDRel_RawPowder", 4, 2.50, 1.00);
        addRecipe("SevenMilAmmoRecast",   "HDRel_RawLead", 1, 1.00, "HDRel_RawBrass",   2, 1.75, "HDRel_RawPowder", 4, 2.50, 1.00);
        addRecipe("SevenMilBrass",        null,            0, 0.00, "HDRel_RawBrass",   0, 1.75, null,              0, 0.00, 1.00);


        // HDBULLETLIB-RECASTED

        // 4ga 00 Buckshot
        addRecipe("HD4GBAmmo",            "HDRel_RawLead", 8, 6.00, "HDRel_RawPlastic", 4, 2.50, "HDRel_RawPowder", 3, 2.00, 0.50);
        addRecipe("HDSpent4GB",           null,            0, 0.00, "HDRel_RawPlastic", 0, 2.50, null,              0, 0.00, 0.50);

        // 4ga Saboted Slug
        addRecipe("HD4GSAmmo",            "HDRel_RawLead", 8, 6.00, "HDRel_RawPlastic", 4, 3.00, "HDRel_RawPowder", 3, 2.00, 0.50);
        addRecipe("HDSpent4GS",           null,            0, 0.00, "HDRel_RawPlastic", 0, 3.00, null,              0, 0.00, 0.50);

        // 5mm MR
        addRecipe("HD5mm_Ammo",           "HDRel_RawLead", 1, 0.50, "HDRel_RawPlastic", 1, 0.50, "HDRel_RawPowder", 1, 0.50, 1.75);
        addRecipe("HDSpent5mmMR",         null,            0, 0.00, "HDRel_RawPlastic", 0, 0.50, null,              0, 0.00, 1.75);

        // 6mm Flechettes
        addRecipe("HD6mmFlechetteAmmo",   "HDRel_RawLead", 2, 1.00, "HDRel_RawPlastic", 1, 0.75, "HDRel_RawPowder", 1, 0.75, 1.25);
        addRecipe("HDSpent6mmFlechette",  null,            0, 0.00, "HDRel_RawPlastic", 0, 0.75, null,              0, 0.00, 1.25);

        // 10mm Auto
        addRecipe("HD10mAmmo",            "HDRel_RawLead", 6, 2.50, "HDRel_RawBrass",   2, 1.50, "HDRel_RawPowder", 3, 1.50, 1.00);
        addRecipe("TenMilBrass",          null,            0, 0.00, "HDRel_RawBrass",   0, 1.50, null,              0, 0.00, 1.00);

        //.30-06
        addRecipe("ThirtyAughtSixAmmo",   "HDRel_RawLead", 3, 2.25, "HDRel_RawBrass",   2, 1.75, "HDRel_RawPowder", 4, 2.50, 0.90);
        addRecipe("ThirtyAughtSixBrass",  null,            0, 0.00, "HDRel_RawBrass",   0, 1.75, null,              0, 0.00, 0.90);

        // .45 ACP
        addRecipe("HD45ACPAmmo",          "HDRel_RawLead", 2, 1.50, "HDRel_RawBrass",   2, 1.00, "HDRel_RawPowder", 2, 1.00, 0.75);
        addRecipe("HDSpent45ACP",         null,            0, 0.00, "HDRel_RawBrass",   0, 1.00, null,              0, 0.00, 0.75);

        // .45 LC
        addRecipe("HD45LCAmmo",           "HDRel_RawLead", 2, 1.50, "HDRel_RawBrass",   2, 1.00, "HDRel_RawPowder", 3, 1.50, 0.75);
        addRecipe("HDSpent45LC",          null,            0, 0.00, "HDRel_RawBrass",   0, 1.00, null,              0, 0.00, 0.75);

        // .45 Golden LC
        addRecipe("HDGold45LCAmmo",       "HDRel_RawLead", 4, 3.00, "HDRel_RawBrass",   2, 1.00, "HDRel_RawPowder", 6, 3.50, 0.75);
        addRecipe("HDSpentGold45lc",      null,            0, 0.00, "HDRel_RawBrass",   0, 1.00, null,              0, 0.00, 0.75);

        // .50 AE
        addRecipe("HD50AEAmmo",           "HDRel_RawLead", 3, 2.25, "HDRel_RawBrass",   2, 1.25, "HDRel_RawPowder", 2, 1.25, 0.75);
        addRecipe("HDSpent50AE",          null,            0, 0.00, "HDRel_RawBrass",   0, 1.25, null,              0, 0.00, 0.75);
        
        // .50 Action-Mega
        addRecipe("HD50AM_Ammo",          "HDRel_RawLead", 3, 2.25, "HDRel_RawBrass",   2, 1.25, "HDRel_RawPowder", 2, 1.00, 0.75);
        addRecipe("HDSpent50AM",          null,            0, 0.00, "HDRel_RawBrass",   0, 1.25, null,              0, 0.00, 0.75);

        // .50 OMG
        addRecipe("HD50OMGAmmo",          "HDRel_RawLead", 5, 3.80, "HDRel_RawBrass",   4, 3.00, "HDRel_RawPowder", 6, 4.00, 0.50);
        addRecipe("HDSpent50OMG",         null,            0, 0.00, "HDRel_RawBrass",   0, 3.00, null,              0, 0.00, 0.50);

        // 56cal Lead Ball
        addRecipe("HDBallAmmo",           "HDRel_RawLead", 5, 5.00, "HDRel_RawBrass",   0, 0.00, "HDRel_RawPowder", 0, 0.00, 0.25);

        // .451 Frei
        addRecipe("HDAurochsAmmo",        "HDRel_RawLead", 2, 1.50, "HDRel_RawPlastic", 2, 1.50, "HDRel_RawPowder", 2, 1.50, 0.90);
        addRecipe("HDSpent420",           null,            0, 0.00, "HDRel_RawPlastic", 1, 1.50, null,              0, 0.00, 0.90);

        // .066 Bore Shell
        addRecipe("HD069BoreAmmo",        "HDRel_RawLead", 2, 1.70, "HDRel_RawPlastic", 2, 1.70, "HDRel_RawPowder", 2, 1.70, 0.90);
        addRecipe("HDSpent069Bore",       null,            0, 0.00, "HDRel_RawPlastic", 1, 1.70, null,              0, 0.00, 0.90);

        // .300 Savage
        addRecipe("Savage300Ammo",        "HDRel_RawLead", 2, 1.25, "HDRel_RawBrass",   2, 1.25, "HDRel_RawPowder", 4, 2.25, 1.20);
        addRecipe("Savage300Brass",       null,            0, 0.00, "HDRel_RawBrass",   2, 1.25, null,              0, 0.00, 1.20);

        // .500 S&W
        addRecipe("HD500SWLightAmmo",     "HDRel_RawLead", 3, 2.25, "HDRel_RawBrass",   2, 1.25, "HDRel_RawPowder", 2, 1.00, 0.75);
        addRecipe("HD500SWHeavyAmmo",     "HDRel_RawLead", 4, 3.00, "HDRel_RawBrass",   2, 1.25, "HDRel_RawPowder", 2, 1.00, 0.75);
        addRecipe("HDSpent500",           null,            0, 0.00, "HDRel_RawBrass",   0, 1.25, null,              0, 0.00, 0.75);

        // .762 Tokarev
        addRecipe("HD762TokarevAmmo",     "HDRel_RawLead", 2, 1.25, "HDRel_RawBrass",   2, 1.25, "HDRel_RawPowder", 4, 2.25, 1.20);
        addRecipe("TokarevBrass",         null,            0, 0.00, "HDRel_RawBrass",   2, 1.25, null,              0, 0.00, 1.20);

        // Birdshot Shells
        addRecipe("HDBirdshotShellAmmo",  "HDRel_RawLead", 4, 3.00, "HDRel_RawPlastic", 2, 1.00, "HDRel_RawPowder", 1, 0.50, 1.00);
        addRecipe("HDSpentBirdshotShell", null,            0, 0.00, "HDRel_RawPlastic", 0, 1.00, null,              0, 0.00, 1.00);

        // Explosive Shells
        addRecipe("HDExplosiveShellAmmo",  "HDRel_RawLead", 4, 1.50, "HDRel_RawPlastic", 2, 1.00, "HDRel_RawPowder", 1, 0.75, 1.00);
        addRecipe("HDSpentExplosiveShell", null,            0, 0.00, "HDRel_RawPlastic", 0, 1.00, null,              0, 0.00, 1.00);

        // Flare Shells
        addRecipe("HDFlareAmmo",           "HDRel_RawLead", 4, 1.50, "HDRel_RawPlastic", 2, 1.00, "HDRel_RawPowder", 1, 0.75, 1.00);

        // Less-Lethal Shells
        addRecipe("HDLLShellAmmo",         "HDRel_RawLead", 2, 0.50, "HDRel_RawPlastic", 2, 1.00, "HDRel_RawPowder", 1, 0.50, 1.00);
        addRecipe("HDLLSpentShell",        null,            0, 0.00, "HDRel_RawPlastic", 0, 1.00, null,              0, 0.00, 1.00);

        // 12ga Slugs
        addRecipe("HDSlugAmmo",            "HDRel_RawLead", 5, 3.00, "HDRel_RawPlastic", 1, 0.75, "HDRel_RawPowder", 2, 1.00, 1.00);
        addRecipe("HDSpentSlug",           null,            0, 0.00, "HDRel_RawPlastic", 0, 0.75, null,              0, 0.00, 1.00);


        // PEPPERGRINDER

        // 9mm NDM
        addRecipe("HDNDMLoose",            "HDRel_RawLead", 4, 2.75, "HDRel_RawBrass",   1, 0.75, "HDRel_RawPowder", 2, 1.00, 1.00);
        addRecipe("HDSpentNDM",            null,            0, 0.00, "HDRel_RawBrass",   0, 0.75, null,              0, 0.00, 1.00);
    }

    // Random stuff, stores it and forces negative values just to be 0.
    bool giveRandom(int chance) {
        if (chance > -1) {
            let result = random(0, chance);

            if (hd_debug) console.printf("Rolled a "..result.." out of "..(chance + 1));

            return result == 0;
        }

        return false;
    }

    // Tries to create the item via random spawning.
    bool tryCreateItem(Inventory item, URLSpawnItem f, int g, bool rep) {
        if (giveRandom(f.spawnReplaces[g].chance)) {
            if (Actor.Spawn(f.spawnName, item.pos) && rep) {
                if (hd_debug) console.printf(item.GetClassName().." -> "..f.spawnName);

                item.destroy();

                return true;
            }
        }

        return false;
    }

    override void worldthingspawned(worldevent e) {
        // Populates the main arrays if they haven't been already. 
        if (!cvarsAvailable) init();

        // If thing spawned doesn't exist, quit
        if (!e.Thing) return;

        // If thing spawned is blacklisted, quit
        for (let i = 0; i < blacklist.size(); i++) if (e.thing is blacklist[i]) return;

        string candidateName = e.Thing.GetClassName();
        candidateName = candidateName.makelower();

        // Pointers for specific classes.
        let material = HDRel_CraftingMaterial(e.Thing);
        let reloader = HDUniversalReloader(e.Thing);

        // If the thing spawned is a crafting material, add any and all items that can use this.
        if (material) handleMaterialUses(material, candidateName);

        // If the thing spawned is a Universal Reloader, copy all the registered recipes.
        if (reloader) reloader.addRecipes(recipes);
    }

    private void handleMaterialUses(HDRel_CraftingMaterial material, string candidateName) {
        // Goes through the entire ammospawn array.
        for (let i = 0; i < ammoSpawnList.size(); i++) {
            if (candidateName == ammoSpawnList[i].ammoName) {
                // Appends each entry in that material's subarray.
                for (let j = 0; j < ammoSpawnList[i].weaponNames.size(); j++) {
                    // Actual pushing to itemsthatusethis().
                    material.ItemsThatUseThis.Push(ammoSpawnList[i].weaponNames[j]);
                }
            }
        }
    }
}