// Struct for itemspawn information.
class URLSpawnItem play {
    // ID by string for spawner
    string spawnName;
    
    // ID by string for spawnees
    Array<URLSpawnItemEntry> spawnReplaces;
    
    // Whether or not to persistently spawn.
    bool isPersistent;
    
    bool replaceItem;

    string toString() {

        let replacements = "[";
        if (spawnReplaces.size()) {
            replacements = replacements..spawnReplaces[0].toString();

            for (let i = 1; i < spawnReplaces.size(); i++) {
                replacements = replacements..", "..spawnReplaces[i].toString();
            }
        }
        replacements = replacements.."]";


        return String.format("{ spawnName=%s, spawnReplaces=%s, isPersistent=%b, replaceItem=%b }", spawnName, replacements, isPersistent, replaceItem);
    }
}

class URLSpawnItemEntry play {
    string name;
    int    chance;

    string toString() {
        return String.format("{ name=%s, chance=%s }", name, chance >= 0 ? "1/"..(chance + 1) : "never");
    }
}

// Struct for passing useinformation to ammunition.
class URLSpawnAmmo play {
    // ID by string for the header ammo.
    string ammoName;
    
    // ID by string for weapons using that ammo.
    Array<string> weaponNames;
    
    string toString() {

        let weapons = "[";
        if (weaponNames.size()) {
            weapons = weapons..weaponNames[0];

            for (let i = 1; i < weaponNames.size(); i++) {
                weapons = weapons..", "..weaponNames[i];
            }
        }
        weapons = weapons.."]";

        return String.format("{ ammoName=%s, weaponNames=%s }", ammoName, weapons);
    }
}



// One handler to rule them all.
class URLSpawnHandler : EventHandler {

    // List of persistent classes to completely ignore.
    // This -should- mean this mod has no performance impact.
    static const class<actor> blacklist[] = {
        "HDSmoke",
        "BloodTrail",
        "CheckPuff",
        "WallChunk",
        "HDBulletPuff",
        "HDFireballTail",
        "ReverseImpBallTail",
        "HDSmokeChunk",
        "ShieldSpark",
        "HDFlameRed",
        "HDMasterBlood",
        "PlantBit",
        "HDBulletActor",
        "HDLadderSection"
    };

    // List of weapon-ammo associations.
    // Used for ammo-use association on ammo spawn (happens very often).
    array<URLSpawnAmmo> ammoSpawnList;

    // List of item-spawn associations.
    // used for item-replacement on mapload.
    array<URLSpawnItem> itemSpawnList;

    Array<HDRel_Recipe> recipes;

    bool cvarsAvailable;

    // appends an entry to itemSpawnList;
    void addItem(string name, Array<URLSpawnItemEntry> replacees, bool persists, bool rep=true) {

        if (hd_debug) {
            let msg = "Adding "..(persists ? "Persistent" : "Non-Persistent").." Replacement Entry for "..name..": ["..replacees[0].toString();

            if (replacees.size() > 1) {
                for (let i = 1; i < replacees.size(); i++) msg = msg..", "..replacees[i].toString();
            }

            console.printf(msg.."]");
        }

        // Creates a new struct;
        URLSpawnItem spawnee = URLSpawnItem(new('URLSpawnItem'));

        // Populates the struct with relevant information,
        spawnee.spawnName = name;
        spawnee.isPersistent = persists;
        spawnee.replaceItem = rep;

        for (int i = 0; i < replacees.size(); i++) {
            spawnee.spawnReplaces.push(replacees[i]);
        }

        // Pushes the finished struct to the array.
        itemSpawnList.push(spawnee);
    }

    URLSpawnItemEntry addItemEntry(string name, int chance) {
        // Creates a new struct;
        URLSpawnItemEntry spawnee = URLSpawnItemEntry(new('URLSpawnItemEntry'));
        spawnee.name = name.makelower();
        spawnee.chance = chance;
        return spawnee;
    }

    // appends an entry to ammoSpawnList;
    void addAmmo(string name, Array<string> weapons) {

        // Creates a new struct;
        URLSpawnAmmo spawnee = URLSpawnAmmo(new('URLSpawnAmmo'));
        spawnee.ammoName = name.makelower();

        // Populates the struct with relevant information,
        for (int i = 0; i < weapons.size(); i++) {
            spawnee.weaponNames.push(weapons[i].makelower());
        }

        // Pushes the finished struct to the array.
        ammoSpawnList.push(spawnee);
    }

    void addRecipe(string amcls, int enabled,
        class<HDRel_CraftingMaterial> projMat,   int projCost, double projProd,
        class<HDRel_CraftingMaterial> casingMat, int csgCost,  double csgProd,
        class<HDRel_CraftingMaterial> powderMat, int pwdCost,  double pwdProd,
        double speed
    ) {
        HDRel_Recipe r;

        if (r = HDRel_Recipe.TryCreate(amcls, enabled,
            projMat, projCost, projProd,
            casingMat, csgCost, csgProd,
            powderMat, pwdCost, pwdProd,
            speed)
        ) {
            if (hd_debug) console.printf("Adding Universal Reloader Crafting Recipe for "..amcls);

            recipes.push(r);
        }
    }


    // Populates the replacement and association arrays.
    void init() {
        
        cvarsAvailable = true;

        //---------------------
        // Crafting Materials
        //---------------------

        Array<String> mat_brass;
        mat_brass.push("HDUniversalReloader");
        addAmmo("HDRel_RawBrass", mat_brass);

        Array<String> mat_lead;
        mat_lead.push("HDUniversalReloader");
        addAmmo("HDRel_RawLead", mat_lead);

        Array<String> mat_plastic;
        mat_plastic.push("HDUniversalReloader");
        addAmmo("HDRel_RawPlastic", mat_plastic);

        Array<String> mat_powder;
        mat_powder.push("HDUniversalReloader");
        addAmmo("HDRel_RawPowder", mat_powder);

        Array<String> mat_steel;
        mat_steel.push("HDUniversalReloader");
        addAmmo("HDRel_RawSteel", mat_steel);

        //---------------------
        // Crafting Recipes
        //---------------------

        string projectileMats[3] = { "", "HDRel_RawLead", "HDRel_RawSteel" };
        string casingMats[4]     = { "", "HDRel_RawBrass", "HDRel_RawPlastic", "HDRel_RawSteel" };
        string powderMats[2]     = { "", "HDRel_RawPowder" };

        //            Crafting Result;         Projectile mat, cost, produced;
        //                                     Casingm Mat,    cost, produced;
        //                                     Powder mat,     cost, produced;
        //                                     Speed.

        // VANILLA HDEST

        // 9mm
        if (url_9mm_enabled) {
            addRecipe("HDPistolAmmo",          url_9mm_enabled,
                                               projectileMats[url_9mm_projMat], url_9mm_projAmt,   url_9mm_projAmt * url_disassemble_ratio,
                                               casingMats[url_9mm_casingMat],   url_9mm_casingAmt, url_9mm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_9mm_powderMat],   url_9mm_powderAmt, url_9mm_powderAmt * url_disassemble_ratio,
                                               url_9mm_speed);
            addRecipe("HDSpent9mm",            url_9mm_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_9mm_casingMat],   url_9mm_casingAmt, url_9mm_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_9mm_speed);
        }

        // .355
        if (url_355_enabled) {
            addRecipe("HDRevolverAmmo",        url_355_enabled,
                                               projectileMats[url_355_projMat], url_355_projAmt,   url_355_projAmt * url_disassemble_ratio,
                                               casingMats[url_355_casingMat],   url_355_casingAmt, url_355_casingAmt * url_disassemble_ratio,
                                               powderMats[url_355_powderMat],   url_355_powderAmt, url_355_powderAmt * url_disassemble_ratio,
                                               url_355_speed);
            addRecipe("HDSpent355",            url_355_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_355_casingMat],   url_355_casingAmt, url_355_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_355_speed);
        }

        // 12ga Shells
        if (url_12gaShells_enabled) {
            addRecipe("HDShellAmmo",           url_12gaShells_enabled,
                                               projectileMats[url_12gaShells_projMat], url_12gaShells_projAmt,   url_12gaShells_projAmt * url_disassemble_ratio,
                                               casingMats[url_12gaShells_casingMat],   url_12gaShells_casingAmt, url_12gaShells_casingAmt * url_disassemble_ratio,
                                               powderMats[url_12gaShells_powderMat],   url_12gaShells_powderAmt, url_12gaShells_powderAmt * url_disassemble_ratio,
                                               url_12gaShells_speed);
            addRecipe("HDSpentShell",          url_12gaShells_enabled,
                                               null,                                   0,                        0.00,
                                               casingMats[url_12gaShells_casingMat],   url_12gaShells_casingAmt, url_12gaShells_casingAmt * url_disassemble_ratio,
                                               null,                                   0,                        0.00,
                                               url_12gaShells_speed);
        }

        // 4.26mm
        if (url_4mm_enabled) {
            // Hardcoded Casing Material away because caseless.
            addRecipe("FourMilAmmo",           url_4mm_enabled,
                                               projectileMats[url_4mm_projMat], url_4mm_projAmt,   url_4mm_projAmt * url_disassemble_ratio,
                                               casingMats[url_4mm_casingMat],   url_4mm_casingAmt, url_4mm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_4mm_powderMat],   url_4mm_powderAmt, url_4mm_powderAmt * url_disassemble_ratio,
                                               url_4mm_speed);
        }

        // 7.76mm
        if (url_7mm_enabled) {
            addRecipe("SevenMilAmmo",          url_7mm_enabled,
                                               projectileMats[url_7mm_projMat], url_7mm_projAmt,   url_7mm_projAmt * url_disassemble_ratio,
                                               casingMats[url_7mm_casingMat],   url_7mm_casingAmt, url_7mm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_7mm_powderMat],   url_7mm_powderAmt, url_7mm_powderAmt * url_disassemble_ratio,
                                               url_7mm_speed);
            addRecipe("SevenMilAmmoRecast",    url_7mm_enabled,
                                               projectileMats[url_7mmRecast_projMat], url_7mmRecast_projAmt,   url_7mmRecast_projAmt * url_disassemble_ratio,
                                               casingMats[url_7mm_casingMat],   url_7mm_casingAmt, url_7mm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_7mm_powderMat],   url_7mm_powderAmt, url_7mm_powderAmt * url_disassemble_ratio,
                                               url_7mm_speed);
            addRecipe("SevenMilBrass",         url_7mm_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_7mm_casingMat],   url_7mm_casingAmt, url_7mm_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_7mm_speed);
        }


        // HDBULLETLIB-RECASTED

        // 4ga 00 Buckshot
        if (url_4gb_enabled) {
            addRecipe("HD4GBAmmo",             url_4gb_enabled,
                                               projectileMats[url_4gb_projMat], url_4gb_projAmt,   url_4gb_projAmt * url_disassemble_ratio,
                                               casingMats[url_4gb_casingMat],   url_4gb_casingAmt, url_4gb_casingAmt * url_disassemble_ratio,
                                               powderMats[url_4gb_powderMat],   url_4gb_powderAmt, url_4gb_powderAmt * url_disassemble_ratio,
                                               url_4gb_speed);
            addRecipe("HDSpent4GB",            url_4gb_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_4gb_casingMat],   url_4gb_casingAmt, url_4gb_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_4gb_speed);
        }

        // 4ga Saboted Slug
        if (url_4gs_enabled) {
            addRecipe("HD4GSAmmo",             url_4gs_enabled,
                                               projectileMats[url_4gs_projMat], url_4gs_projAmt,   url_4gs_projAmt * url_disassemble_ratio,
                                               casingMats[url_4gs_casingMat],   url_4gs_casingAmt, url_4gs_casingAmt * url_disassemble_ratio,
                                               powderMats[url_4gs_powderMat],   url_4gs_powderAmt, url_4gs_powderAmt * url_disassemble_ratio,
                                               url_4gs_speed);
            addRecipe("HDSpent4GS",            url_4gs_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_4gs_casingMat],   url_4gs_casingAmt, url_4gs_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_4gs_speed);
        }

        // 5mm MR
        if (url_5mm_enabled) {
            addRecipe("HD5mm_Ammo",            url_5mm_enabled,
                                               projectileMats[url_5mm_projMat], url_5mm_projAmt,   url_5mm_projAmt * url_disassemble_ratio,
                                               casingMats[url_5mm_casingMat],   url_5mm_casingAmt, url_5mm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_5mm_powderMat],   url_5mm_powderAmt, url_5mm_powderAmt * url_disassemble_ratio,
                                               url_5mm_speed);
            addRecipe("HDSpent5mmMR",          url_5mm_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_5mm_casingMat],   url_5mm_casingAmt, url_5mm_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_5mm_speed);
        }

        // 6mm Flechettes
        if (url_6mm_enabled) {
            addRecipe("HD6mmFlechetteAmmo",    url_6mm_enabled,
                                               projectileMats[url_6mm_projMat], url_6mm_projAmt,   url_6mm_projAmt * url_disassemble_ratio,
                                               casingMats[url_6mm_casingMat],   url_6mm_casingAmt, url_6mm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_6mm_powderMat],   url_6mm_powderAmt, url_6mm_powderAmt * url_disassemble_ratio,
                                               url_6mm_speed);
            addRecipe("HDSpent6mmFlechette",   url_6mm_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_6mm_casingMat],   url_6mm_casingAmt, url_6mm_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_6mm_speed);
        }

        // 10mm Auto
        if (url_10mm_enabled) {
            addRecipe("HD10mAmmo",             url_10mm_enabled,
                                               projectileMats[url_10mm_projMat], url_10mm_projAmt,   url_10mm_projAmt * url_disassemble_ratio,
                                               casingMats[url_10mm_casingMat],   url_10mm_casingAmt, url_10mm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_10mm_powderMat],   url_10mm_powderAmt, url_10mm_powderAmt * url_disassemble_ratio,
                                               url_10mm_speed);
            addRecipe("TenMilBrass",           url_10mm_enabled,
                                               null,                             0,                  0.00,
                                               casingMats[url_10mm_casingMat],   url_10mm_casingAmt, url_10mm_casingAmt * url_disassemble_ratio,
                                               null,                             0,                  0.00,
                                               url_10mm_speed);
        }

        //.30-06
        if (url_3006_enabled) {
            addRecipe("ThirtyAughtSixAmmo",    url_3006_enabled,
                                               projectileMats[url_3006_projMat], url_3006_projAmt,   url_3006_projAmt * url_disassemble_ratio,
                                               casingMats[url_3006_casingMat],   url_3006_casingAmt, url_3006_casingAmt * url_disassemble_ratio,
                                               powderMats[url_3006_powderMat],   url_3006_powderAmt, url_3006_powderAmt * url_disassemble_ratio,
                                               url_3006_speed);
            addRecipe("ThirtyAughtSixBrass",   url_3006_enabled,
                                               null,                             0,                  0.00,
                                               casingMats[url_3006_casingMat],   url_3006_casingAmt, url_3006_casingAmt * url_disassemble_ratio,
                                               null,                             0,                  0.00,
                                               url_3006_speed);
        }

        // .45 ACP
        if (url_45acp_enabled) {
            addRecipe("HD45ACPAmmo",           url_45acp_enabled,
                                               projectileMats[url_45acp_projMat], url_45acp_projAmt,   url_45acp_projAmt * url_disassemble_ratio,
                                               casingMats[url_45acp_casingMat],   url_45acp_casingAmt, url_45acp_casingAmt * url_disassemble_ratio,
                                               powderMats[url_45acp_powderMat],   url_45acp_powderAmt, url_45acp_powderAmt * url_disassemble_ratio,
                                               url_45acp_speed);
            addRecipe("HDSpent45ACP",          url_45acp_enabled,
                                               null,                              0,                   0.00,
                                               casingMats[url_45acp_casingMat],   url_45acp_casingAmt, url_45acp_casingAmt * url_disassemble_ratio,
                                               null,                              0,                   0.00,
                                               url_45acp_speed);
        }

        // .45 LC
        if (url_45lc_enabled) {
            addRecipe("HD45LCAmmo",            url_45lc_enabled,
                                               projectileMats[url_45lc_projMat], url_45lc_projAmt,   url_45lc_projAmt * url_disassemble_ratio,
                                               casingMats[url_45lc_casingMat],   url_45lc_casingAmt, url_45lc_casingAmt * url_disassemble_ratio,
                                               powderMats[url_45lc_powderMat],   url_45lc_powderAmt, url_45lc_powderAmt * url_disassemble_ratio,
                                               url_45lc_speed);
            addRecipe("HDSpent45LC",           url_45lc_enabled,
                                               null,                             0,                  0.00,
                                               casingMats[url_45lc_casingMat],   url_45lc_casingAmt, url_45lc_casingAmt * url_disassemble_ratio,
                                               null,                             0,                  0.00,
                                               url_45lc_speed);
        }

        // .45 Golden LC
        if (url_g45lc_enabled) {
            addRecipe("HDGold45LCAmmo",        url_g45lc_enabled,
                                               projectileMats[url_g45lc_projMat], url_g45lc_projAmt,   url_g45lc_projAmt * url_disassemble_ratio,
                                               casingMats[url_g45lc_casingMat],   url_g45lc_casingAmt, url_g45lc_casingAmt * url_disassemble_ratio,
                                               powderMats[url_g45lc_powderMat],   url_g45lc_powderAmt, url_g45lc_powderAmt * url_disassemble_ratio,
                                               url_g45lc_speed);
            addRecipe("HDSpentGold45lc",       url_g45lc_enabled,
                                               null,                              0,                   0.00,
                                               casingMats[url_g45lc_casingMat],   url_g45lc_casingAmt, url_g45lc_casingAmt * url_disassemble_ratio,
                                               null,                              0,                   0.00,
                                               url_g45lc_speed);
        }

        // .50 AE
        if (url_50ae_enabled) {
            addRecipe("HD50AEAmmo",            url_50ae_enabled,
                                               projectileMats[url_50ae_projMat], url_50ae_projAmt,   url_50ae_projAmt * url_disassemble_ratio,
                                               casingMats[url_50ae_casingMat],   url_50ae_casingAmt, url_50ae_casingAmt * url_disassemble_ratio,
                                               powderMats[url_50ae_powderMat],   url_50ae_powderAmt, url_50ae_powderAmt * url_disassemble_ratio,
                                               url_50ae_speed);
            addRecipe("HDSpent50AE",           url_50ae_enabled,
                                               null,                             0,                  0.00,
                                               casingMats[url_50ae_casingMat],   url_50ae_casingAmt, url_50ae_casingAmt * url_disassemble_ratio,
                                               null,                             0,                  0.00,
                                               url_50ae_speed);
        }
        
        // .50 Action-Mega
        if (url_50am_enabled) {
            addRecipe("HD50AM_Ammo",           url_50am_enabled,
                                               projectileMats[url_50am_projMat], url_50am_projAmt,   url_50am_projAmt * url_disassemble_ratio,
                                               casingMats[url_50am_casingMat],   url_50am_casingAmt, url_50am_casingAmt * url_disassemble_ratio,
                                               powderMats[url_50am_powderMat],   url_50am_powderAmt, url_50am_powderAmt * url_disassemble_ratio,
                                               url_50am_speed);
            addRecipe("HDSpent50AM",           url_50am_enabled,
                                               null,                             0,                  0.00,
                                               casingMats[url_50am_casingMat],   url_50am_casingAmt, url_50am_casingAmt * url_disassemble_ratio,
                                               null,                             0,                  0.00,
                                               url_50am_speed);
        }

        // .50 OMG
        if (url_50omg_enabled) {
            addRecipe("HD50OMGAmmo",           url_50omg_enabled,
                                               projectileMats[url_50omg_projMat], url_50omg_projAmt,   url_50omg_projAmt * url_disassemble_ratio,
                                               casingMats[url_50omg_casingMat],   url_50omg_casingAmt, url_50omg_casingAmt * url_disassemble_ratio,
                                               powderMats[url_50omg_powderMat],   url_50omg_powderAmt, url_50omg_powderAmt * url_disassemble_ratio,
                                               url_50omg_speed);
            addRecipe("HDSpent50OMG",          url_50omg_enabled,
                                               null,                              0,                   0.00,
                                               casingMats[url_50omg_casingMat],   url_50omg_casingAmt, url_50omg_casingAmt * url_disassemble_ratio,
                                               null,                              0,                   0.00,
                                               url_50omg_speed);
        }

        // 56cal Lead Ball
        if (url_mball_enabled) {
            addRecipe("HDBallAmmo",            url_mball_enabled,
                                               projectileMats[url_mball_projMat], url_mball_projAmt,   url_mball_projAmt * url_disassemble_ratio,
                                               casingMats[url_mball_casingMat],   url_mball_casingAmt, url_mball_casingAmt * url_disassemble_ratio,
                                               powderMats[url_mball_powderMat],   url_mball_powderAmt, url_mball_powderAmt * url_disassemble_ratio,
                                               url_mball_speed);
        }

        // .451 Frei
        if (url_420_enabled) {
            addRecipe("HDAurochsAmmo",         url_420_enabled,
                                               projectileMats[url_420_projMat], url_420_projAmt,   url_420_projAmt * url_disassemble_ratio,
                                               casingMats[url_420_casingMat],   url_420_casingAmt, url_420_casingAmt * url_disassemble_ratio,
                                               powderMats[url_420_powderMat],   url_420_powderAmt, url_420_powderAmt * url_disassemble_ratio,
                                               url_420_speed);
            addRecipe("HDSpent420",            url_420_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_420_casingMat],   url_420_casingAmt, url_420_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_420_speed);
        }

        // .066 Bore Shell
        if (url_069_enabled) {
            addRecipe("HD069BoreAmmo",         url_069_enabled,
                                               projectileMats[url_069_projMat], url_069_projAmt,   url_069_projAmt * url_disassemble_ratio,
                                               casingMats[url_069_casingMat],   url_069_casingAmt, url_069_casingAmt * url_disassemble_ratio,
                                               powderMats[url_069_powderMat],   url_069_powderAmt, url_069_powderAmt * url_disassemble_ratio,
                                               url_069_speed);
            addRecipe("HDSpent069Bore",        url_069_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_069_casingMat],   url_069_casingAmt, url_069_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_069_speed);
        }

        // .300 Savage
        if (url_300savage_enabled) {
            addRecipe("Savage300Ammo",         url_3006_enabled,
                                               projectileMats[url_300savage_projMat], url_300savage_projAmt,   url_300savage_projAmt * url_disassemble_ratio,
                                               casingMats[url_300savage_casingMat],   url_300savage_casingAmt, url_300savage_casingAmt * url_disassemble_ratio,
                                               powderMats[url_300savage_powderMat],   url_300savage_powderAmt, url_300savage_powderAmt * url_disassemble_ratio,
                                               url_300savage_speed);
            addRecipe("Savage300Brass",        url_3006_enabled,
                                               null,                                  0,                       0.00,
                                               casingMats[url_300savage_casingMat],   url_300savage_casingAmt, url_300savage_casingAmt * url_disassemble_ratio,
                                               null,                                  0,                       0.00,
                                               url_300savage_speed);
        }

        // .500 S&W
        if (url_500sw_enabled) {
            addRecipe("HD500SWLightAmmo",      url_500sw_enabled,
                                               projectileMats[url_500swl_projMat], url_500swl_projAmt,   url_500swl_projAmt * url_disassemble_ratio,
                                               casingMats[url_500sw_casingMat],   url_500sw_casingAmt, url_500sw_casingAmt * url_disassemble_ratio,
                                               powderMats[url_500sw_powderMat],   url_500sw_powderAmt, url_500sw_powderAmt * url_disassemble_ratio,
                                               url_500sw_speed);
            addRecipe("HD500SWHeavyAmmo",      url_500sw_enabled,
                                               projectileMats[url_500swh_projMat], url_500swh_projAmt,   url_500swh_projAmt * url_disassemble_ratio,
                                               casingMats[url_500sw_casingMat],   url_500sw_casingAmt, url_500sw_casingAmt * url_disassemble_ratio,
                                               powderMats[url_500sw_powderMat],   url_500sw_powderAmt, url_500sw_powderAmt * url_disassemble_ratio,
                                               url_500sw_speed);
            addRecipe("HDSpent500",            url_500sw_enabled,
                                               null,                              0,                   0.00,
                                               casingMats[url_500sw_casingMat],   url_500sw_casingAmt, url_500sw_casingAmt * url_disassemble_ratio,
                                               null,                              0,                   0.00,
                                               url_500sw_speed);
        }

        // .762 Tokarev
        if (url_762tokarev_enabled) {
            addRecipe("HD762TokarevAmmo",      url_762tokarev_enabled,
                                               projectileMats[url_762tokarev_projMat], url_762tokarev_projAmt,   url_762tokarev_projAmt * url_disassemble_ratio,
                                               casingMats[url_762tokarev_casingMat],   url_762tokarev_casingAmt, url_762tokarev_casingAmt * url_disassemble_ratio,
                                               powderMats[url_762tokarev_powderMat],   url_762tokarev_powderAmt, url_762tokarev_powderAmt * url_disassemble_ratio,
                                               url_762tokarev_speed);
            addRecipe("TokarevBrass",          url_762tokarev_enabled,
                                               null,                                   0,                        0.00,
                                               casingMats[url_762tokarev_casingMat],   url_762tokarev_casingAmt, url_762tokarev_casingAmt * url_disassemble_ratio,
                                               null,                                   0,                        0.00,
                                               url_762tokarev_speed);
        }

        // Birdshot Shells
        if (url_birdshot_enabled) {
            addRecipe("HDBirdshotShellAmmo",   url_birdshot_enabled,
                                               projectileMats[url_birdshot_projMat], url_birdshot_projAmt,   url_birdshot_projAmt * url_disassemble_ratio,
                                               casingMats[url_birdshot_casingMat],   url_birdshot_casingAmt, url_birdshot_casingAmt * url_disassemble_ratio,
                                               powderMats[url_birdshot_powderMat],   url_birdshot_powderAmt, url_birdshot_powderAmt * url_disassemble_ratio,
                                               url_birdshot_speed);
            addRecipe("HDSpentBirdshotShell",  url_birdshot_enabled,
                                               null,                                 0,                      0.00,
                                               casingMats[url_birdshot_casingMat],   url_birdshot_casingAmt, url_birdshot_casingAmt * url_disassemble_ratio,
                                               null,                                 0,                      0.00,
                                               url_birdshot_speed);
        }

        // Explosive Shells
        if (url_explosiveShells_enabled) {
            addRecipe("HDExplosiveShellAmmo",  url_explosiveShells_enabled,
                                               projectileMats[url_explosiveShells_projMat], url_explosiveShells_projAmt,   url_explosiveShells_projAmt * url_disassemble_ratio,
                                               casingMats[url_explosiveShells_casingMat],   url_explosiveShells_casingAmt, url_explosiveShells_casingAmt * url_disassemble_ratio,
                                               powderMats[url_explosiveShells_powderMat],   url_explosiveShells_powderAmt, url_explosiveShells_powderAmt * url_disassemble_ratio,
                                               url_explosiveShells_speed);
            addRecipe("HDSpentExplosiveShell", url_explosiveShells_enabled,
                                               null,                                        0,                             0.00,
                                               casingMats[url_explosiveShells_casingMat],   url_explosiveShells_casingAmt, url_explosiveShells_casingAmt * url_disassemble_ratio,
                                               null,                                        0,                             0.00,
                                               url_explosiveShells_speed);
        }

        // Flare Shells
        if (url_flareShells_enabled) {
            addRecipe("HDFlareAmmo",           url_flareShells_enabled,
                                               projectileMats[url_flareShells_projMat], url_flareShells_projAmt,   url_flareShells_projAmt * url_disassemble_ratio,
                                               casingMats[url_flareShells_casingMat],   url_flareShells_casingAmt, url_flareShells_casingAmt * url_disassemble_ratio,
                                               powderMats[url_flareShells_powderMat],   url_flareShells_powderAmt, url_flareShells_powderAmt * url_disassemble_ratio,
                                               url_flareShells_speed);
        }

        // Less-Lethal Shells
        if (url_llShells_enabled) {
            addRecipe("HDLLShellAmmo",         url_llShells_enabled,
                                               projectileMats[url_llShells_projMat], url_llShells_projAmt,   url_llShells_projAmt * url_disassemble_ratio,
                                               casingMats[url_llShells_casingMat],   url_llShells_casingAmt, url_llShells_casingAmt * url_disassemble_ratio,
                                               powderMats[url_llShells_powderMat],   url_llShells_powderAmt, url_llShells_powderAmt * url_disassemble_ratio,
                                               url_llShells_speed);
            addRecipe("HDLLSpentShell",        url_llShells_enabled,
                                               null,                                 0,                      0.00,
                                               casingMats[url_llShells_casingMat],   url_llShells_casingAmt, url_llShells_casingAmt * url_disassemble_ratio,
                                               null,                                 0,                      0.00,
                                               url_llShells_speed);
        }

        // 12ga Slugs
        if (url_12gaSlugs_enabled) {
            addRecipe("HDSlugAmmo",            url_12gaSlugs_enabled,
                                               projectileMats[url_12gaSlugs_projMat], url_12gaSlugs_projAmt,   url_12gaSlugs_projAmt * url_disassemble_ratio,
                                               casingMats[url_12gaSlugs_casingMat],   url_12gaSlugs_casingAmt, url_12gaSlugs_casingAmt * url_disassemble_ratio,
                                               powderMats[url_12gaSlugs_powderMat],   url_12gaSlugs_powderAmt, url_12gaSlugs_powderAmt * url_disassemble_ratio,
                                               url_12gaSlugs_speed);
            addRecipe("HDSpentSlug",           url_12gaSlugs_enabled,
                                               null,                                  0,                       0.00,
                                               casingMats[url_12gaSlugs_casingMat],   url_12gaSlugs_casingAmt, url_12gaSlugs_casingAmt * url_disassemble_ratio,
                                               null,                                  0,                       0.00,
                                               url_12gaSlugs_speed);
        }


        // PEPPERGRINDER

        // 9mm NDM
        if (url_ndm_enabled) {
            addRecipe("HDNDMLoose",            url_ndm_enabled,
                                               projectileMats[url_ndm_projMat], url_ndm_projAmt,   url_ndm_projAmt * url_disassemble_ratio,
                                               casingMats[url_ndm_casingMat],   url_ndm_casingAmt, url_ndm_casingAmt * url_disassemble_ratio,
                                               powderMats[url_ndm_powderMat],   url_ndm_powderAmt, url_ndm_powderAmt * url_disassemble_ratio,
                                               url_ndm_speed);
            addRecipe("HDSpentNDM",            url_ndm_enabled,
                                               null,                            0,                 0.00,
                                               casingMats[url_ndm_casingMat],   url_ndm_casingAmt, url_ndm_casingAmt * url_disassemble_ratio,
                                               null,                            0,                 0.00,
                                               url_ndm_speed);
        }
    }

    // Random stuff, stores it and forces negative values just to be 0.
    bool giveRandom(int chance) {
        if (chance > -1) {
            let result = random(0, chance);

            if (hd_debug) console.printf("Rolled a "..result.." out of "..(chance + 1));

            return result == 0;
        }

        return false;
    }

    // Tries to create the item via random spawning.
    bool tryCreateItem(Inventory item, URLSpawnItem f, int g, bool rep) {
        if (giveRandom(f.spawnReplaces[g].chance)) {
            if (Actor.Spawn(f.spawnName, item.pos) && rep) {
                if (hd_debug) console.printf(item.GetClassName().." -> "..f.spawnName);

                item.destroy();

                return true;
            }
        }

        return false;
    }

    override void worldthingspawned(worldevent e) {
        // Populates the main arrays if they haven't been already. 
        if (!cvarsAvailable) init();

        // If thing spawned doesn't exist, quit
        if (!e.Thing) return;

        // If thing spawned is blacklisted, quit
        for (let i = 0; i < blacklist.size(); i++) if (e.thing is blacklist[i]) return;

        string candidateName = e.Thing.GetClassName();
        candidateName = candidateName.makelower();

        // Pointers for specific classes.
        let material = HDRel_CraftingMaterial(e.Thing);
        let reloader = HDUniversalReloader(e.Thing);

        // If the thing spawned is a crafting material, add any and all items that can use this.
        if (material) handleMaterialUses(material, candidateName);

        // If the thing spawned is a Universal Reloader, copy all the registered recipes.
        if (reloader) reloader.addRecipes(recipes);
    }

    private void handleMaterialUses(HDRel_CraftingMaterial material, string candidateName) {
        // Goes through the entire ammospawn array.
        for (let i = 0; i < ammoSpawnList.size(); i++) {
            if (candidateName == ammoSpawnList[i].ammoName) {
                // Appends each entry in that material's subarray.
                for (let j = 0; j < ammoSpawnList[i].weaponNames.size(); j++) {
                    // Actual pushing to itemsthatusethis().
                    material.ItemsThatUseThis.Push(ammoSpawnList[i].weaponNames[j]);
                }
            }
        }
    }
}