class HDRel_RawSteel : HDRel_CraftingMaterial
{
    Default
    {
        Tag "$TAG_RAWSTEEL";
        Inventory.Icon "STMTA0";
        Inventory.PickupMessage "$PICKUP_RAWSTEEL";
		HDRel_CraftingMaterial.PileMessage "$PICKUP_PILE_RAWSTEEL";
		HDRel_CraftingMaterial.PileType PType_Ball;
        HDPickup.Bulk 0.28;
    }

    States
    {
        Spawn:
            STMT A -1;
            Stop;
    }
}